name: example-overleaf
title: Overleaf integration example
description: A Calkit project that demonstrates integrating with 
  Overleaf to edit a publication.
git_repo_url: https://github.com/calkit/example-overleaf
derived_from:
  project: calkit/example-basic
  git_repo_url: https://github.com/calkit/example-basic
  git_rev: 42f00837f638936adad7faf1790058ed0c625ce8

dependencies:
  - docker
  - conda

environments:
  py:
    path: environment.yml
    kind: conda
    description: A Python environment
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    wdir: /work
    description: TeX Live via Docker.

pipeline:
  stages:
    collect-data:
      kind: python-script
      script_path: scripts/collect-data.py
      environment: py
      outputs:
        - data/raw/data.csv
    plot-voltage:
      kind: python-script
      script_path: scripts/plot-voltage.py
      environment: py
      inputs:
        - data/raw/data.csv
      outputs:
        - figures/voltage-time-series.png
    map-paths:
      kind: map-paths
      paths:
        - src: figures
          dest: paper/figures
          kind: dir-to-dir-merge
        - src: references.bib
          dest: paper
          kind: file-to-dir
    build-paper:
      kind: latex
      environment: tex
      target_path: paper/paper.tex
      inputs:
        - from_stage_outputs: map-paths
      outputs:
        - paper/paper.pdf

datasets:
  - path: data/raw/data.csv
    title: Raw data
    description: This is raw voltage data.
    stage: collect-data

figures:
  - path: figures/voltage-time-series.png
    title: Raw voltage time series
    description: A plot of the raw voltage time series.
    stage: plot-voltage

publications:
  - path: paper/paper.pdf
    title: The paper
    description: This is the paper.
    kind: journal-article
    stage: build-paper
showcase:
  - publication: paper/paper.pdf

references:
  - path: references.bib

overleaf_sync:
  paper:
    url: https://www.overleaf.com/project/68000059d42b134573cb2e35
    push_paths: # Always push these to Overleaf
      - figures
