stages:
  collect-data:
    cmd: calkit xenv -n py -- python scripts/collect-data.py
    deps:
      - scripts/collect-data.py
      - environment.yml
    outs:
      - data/raw/data.csv
  plot-voltage:
    cmd: calkit xenv -n py -- python scripts/plot-voltage.py
    deps:
      - scripts/plot-voltage.py
      - data/raw/data.csv
      - environment.yml
    outs:
      - figures/voltage-time-series.png
  copy-figures-to-paper-dir:
    cmd: cp -rf figures paper
    deps:
      - figures
    outs:
      - paper/figures:
          cache: false
  build-paper:
    cmd: >
      calkit xenv -n tex --
      latexmk -cd -interaction=nonstopmode -pdf paper/paper.tex
    deps:
      - paper/figures
      - paper/paper.tex
    outs:
      - paper/paper.pdf
